"""
Django settings for zipcode_notifier project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
from decouple import config


def resolve_path(value):
    """Convert an env-provided path into one rooted under the project directory."""
    path = Path(value)
    return path if path.is_absolute() else BASE_DIR / path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Keep all data paths configurable while resolving relative values consistently from the project root.
DATA_DIR = BASE_DIR / 'data'
INBOX_DIR = resolve_path(config('INBOX_DIR', default=str(DATA_DIR / 'inbox')))
OUTPUT_DIR = resolve_path(config('OUTPUT_DIR', default=str(DATA_DIR / 'output')))
PROCESSED_DIR = resolve_path(config('PROCESSED_DIR', default=str(DATA_DIR / 'processed')))
ERROR_DIR = resolve_path(config('ERROR_DIR', default=str(DATA_DIR / 'error')))
LOGS_DIR = resolve_path(config('LOGS_DIR', default=str(BASE_DIR / 'logs')))

# Create the data and log directories early so they are ready for future processing steps.
for directory in (INBOX_DIR, OUTPUT_DIR, PROCESSED_DIR, ERROR_DIR, LOGS_DIR):
    directory.mkdir(parents=True, exist_ok=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='dev-secret-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'processor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'zipcode_notifier.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'zipcode_notifier.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': config(
            'EMAIL_BACKEND',
            default='django.core.mail.backends.console.EmailBackend',
        ),
        'OPTIONS': {},
    },
}

# Only load SMTP connection details when SMTP is selected; the console backend needs no credentials.
if MAILERS['default']['BACKEND'] == 'django.core.mail.backends.smtp.EmailBackend':
    MAILERS['default']['OPTIONS'] = {
        'host': config('EMAIL_HOST', default='localhost'),
        'port': config('EMAIL_PORT', default=25, cast=int),
        'use_tls': config('EMAIL_USE_TLS', default=False, cast=bool),
        'username': config('EMAIL_HOST_USER', default=''),
        'password': config('EMAIL_HOST_PASSWORD', default=''),
        'timeout': config('EMAIL_TIMEOUT', default=10, cast=int),
    }

DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='zip-notifier@example.com')

# Send logs to both the console and a persistent file so command output and run history are available.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(asctime)s %(levelname)s %(name)s %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': str(LOGS_DIR / 'zipcode_notifier.log'),
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
}
